export const OPEN_MODAL = 'OPEN_MODAL';
export const OPEN_MODAL_ARROW = 'OPEN_MODAL_ARROW';
export const UPDATE_EDIT = 'UPDATE_EDIT';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const FETCH_MESSAGE = 'FETCH_MESSAGE';
export const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS';
export const EDIT_MODAL_FAIL = 'EDIT_MODAL_FAIL';