export const ADD_MESSAGE = 'ADD_MESSAGE';
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const LIKE_MESSAGE = 'LIKE_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL';
